//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int Ci { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> Fecha_Nac { get; set; }
        public Nullable<int> Tel { get; set; }
        public string Direccion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public Nullable<int> RUT_Empresa { get; set; }
    
        public virtual Empresas Empresas { get; set; }
    }
}
