//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public int Tipo_EventoRef { get; set; }
        public int VehiculoRef { get; set; }
        public Nullable<double> Latitud { get; set; }
        public Nullable<double> Longitud { get; set; }
    
        public virtual Tipo_Eventos Tipo_Evento { get; set; }
        public virtual Vehiculos Vehiculos { get; set; }
    }
}
