//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Eventos()
        {
            this.Vehiculos = new HashSet<Vehiculos>();
            this.Eventos = new HashSet<Eventos>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Periodo { get; set; }
        public Nullable<int> Maximo { get; set; }
        public Nullable<int> Minimo { get; set; }
        public string Accion { get; set; }
        public Nullable<bool> Activo { get; set; }
        public string Nombre { get; set; }
        public string Tipo_Sensor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vehiculos> Vehiculos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Eventos> Eventos { get; set; }
    }
}
